# Generated by Django 2.2.6 on 2019-10-24 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='email',
            field=models.EmailField(default='abc@xyz', max_length=254),
            preserve_default=False,
        ),
    ]
